/* GENERATED by make-routes.py from patches/shim/routes/hs-approval-queue.json.
   Do not edit — edit the JSON and rebuild. */
window.MAZE_ROUTES = {
  "proto": "hs-approval-queue",
  "routes": [
    {
      "params": {
        "screen": "path-select"
      },
      "slug": "entry"
    },
    {
      "params": {
        "screen": "email"
      },
      "slug": "email"
    },
    {
      "params": {
        "screen": "login"
      },
      "slug": "sign-in"
    },
    {
      "params": {
        "screen": "service-select"
      },
      "slug": "choose-service"
    },
    {
      "params": {
        "screen": "dashboard"
      },
      "slug": "workspace"
    },
    {
      "params": {
        "screen": "de"
      },
      "slug": "applications"
    },
    {
      "params": {
        "mode": "all",
        "screen": "de",
        "seg": "needs-review"
      },
      "slug": "applications-needs-review"
    },
    {
      "params": {
        "mode": "all",
        "screen": "de",
        "seg": "waiting"
      },
      "slug": "applications-waiting"
    },
    {
      "params": {
        "mode": "all",
        "screen": "de",
        "seg": "active"
      },
      "slug": "applications-registered"
    },
    {
      "params": {
        "mode": "all",
        "screen": "de",
        "seg": "denied"
      },
      "slug": "applications-closed"
    },
    {
      "params": {
        "mode": "review",
        "screen": "de"
      },
      "slug": "review-queue"
    },
    {
      "params": {
        "screen": "review"
      },
      "slug": "application"
    },
    {
      "params": {
        "screen": "deny"
      },
      "slug": "deny"
    },
    {
      "params": {
        "screen": "bulk-approve"
      },
      "slug": "approve-selected"
    },
    {
      "params": {
        "screen": "invites"
      },
      "slug": "pending-invites"
    },
    {
      "params": {
        "screen": "invite-learners"
      },
      "slug": "invite-learners"
    },
    {
      "params": {
        "screen": "invite-college"
      },
      "slug": "invite-institution"
    },
    {
      "params": {
        "screen": "invite-groups"
      },
      "slug": "invite-groups"
    },
    {
      "params": {
        "screen": "add-learners"
      },
      "slug": "add-learners"
    },
    {
      "params": {
        "screen": "bulk-upload"
      },
      "slug": "upload-learners"
    },
    {
      "params": {
        "screen": "edit-learner"
      },
      "slug": "edit-learner"
    },
    {
      "params": {
        "screen": "edit-groups"
      },
      "slug": "edit-groups"
    },
    {
      "params": {
        "screen": "active-enrollments"
      },
      "slug": "enrollments"
    }
  ]
};
