/* GENERATED by make-routes.py from patches/shim/routes/learner-application.json.
   Do not edit — edit the JSON and rebuild. */
window.MAZE_ROUTES = {
  "proto": "learner-application",
  "routes": [
    {
      "params": {
        "screen": "path-select"
      },
      "slug": "entry"
    },
    {
      "params": {
        "screen": "dashboard"
      },
      "slug": "dashboard"
    },
    {
      "params": {
        "screen": "de-tab"
      },
      "slug": "dual-enrollment"
    },
    {
      "params": {
        "screen": "entry"
      },
      "slug": "get-started"
    },
    {
      "params": {
        "screen": "select-hs"
      },
      "slug": "choose-school"
    },
    {
      "params": {
        "screen": "select-college"
      },
      "slug": "choose-college"
    },
    {
      "params": {
        "screen": "college-site"
      },
      "slug": "college-site"
    },
    {
      "params": {
        "screen": "email-landing"
      },
      "slug": "invitation"
    },
    {
      "params": {
        "screen": "email-entry"
      },
      "slug": "your-email"
    },
    {
      "params": {
        "screen": "login"
      },
      "slug": "sign-in"
    },
    {
      "params": {
        "screen": "aer"
      },
      "slug": "create-account"
    },
    {
      "params": {
        "screen": "confirm-email"
      },
      "slug": "confirm-email"
    },
    {
      "params": {
        "screen": "de-app"
      },
      "slug": "application"
    },
    {
      "params": {
        "screen": "aer-confirm"
      },
      "slug": "submitted"
    },
    {
      "params": {
        "screen": "courses"
      },
      "slug": "courses"
    },
    {
      "params": {
        "screen": "course-detail"
      },
      "slug": "course"
    },
    {
      "params": {
        "screen": "registered"
      },
      "slug": "registered"
    }
  ]
};
