/* GENERATED by make-routes.py from patches/shim/routes/parent-consent.json.
   Do not edit — edit the JSON and rebuild. */
window.MAZE_ROUTES = {
  "proto": "parent-consent",
  "routes": [
    {
      "params": {
        "screen": "inbox"
      },
      "slug": "inbox"
    },
    {
      "params": {
        "screen": "find-enrollment"
      },
      "slug": "find-enrollment"
    },
    {
      "params": {
        "screen": "consent"
      },
      "slug": "consent"
    },
    {
      "params": {
        "screen": "success"
      },
      "slug": "submitted"
    }
  ]
};
